# Generated by Django 5.0.2 on 2024-02-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoListdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nametitle', models.CharField(max_length=255)),
                ('namedescription', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='TodoList',
        ),
    ]
